#!/bin/bash


input="$PWD" # set variable as current path in case no path is specified

if (( "$#" >= 2 ))
then
	echo "Usage: pathdisplay [dir-name]"
	exit 1 
fi

if (( "$#" > 0 ))
then
	input=$1
fi

if [ ! -d $input ]
then
	echo "$input is not a valid directory name"
	exit 1
fi

path=`readlink -f $input` # get the absolute path of the directory
textpath=`echo $path` # get the absolute path in string form

dirs=$(IFS=/; set -f; set -- $path; echo $#) # get number of directories (besides root)

i="2" #while loop prints entire textpath, add if statement to see if first in array, if so, then print without the $d

dirArray[$i]=`echo $textpath | awk -F '/' '{print $n }' n=$i`

dirName=${dirArray[$i]}

dirNameArray[$i]=$dirName


i=$[$i+1]

while (( $i <= $dirs )) # store each level by itself in an array spot
do
	dirArray[$i]=`echo $textpath | awk -F '/' '{print "/" $e }' e=$i`
	
	dirName=$dirName${dirArray[$i]}

	dirNameArray[$i]=$dirName

	i=$[$i+1]
done

maxLevel=$i # set maxLevel as the max level
currentLevel=$maxLevel

# all done, now dirNameArray stores each directory in its absolute path in each of its array spots, next we must use it to loop through and display the permissions

#dirs=$((dirs + 1)) # add root(?) maybe?

while [ "$options" != "q" ]; do #until q is pressed, loop
	echo "Owner   Group   Other   Filename"
	echo "-----   -----   -----   --------"
	echo " "
	ls -ld / | awk -F 'd' '{print $2}' | awk '{gsub(/.{3}/,"& ")}1'  | awk '{print $1 " " $2 " " $3 }' | awk '{gsub(/.{1}/,"& ")}1' | awk -F '.' '{print $1 "  /"}' # print only the permissions for the root folder
	echo " "

	dirName=""
	options=""

	x="2"
	while (( $x <= $dirs )) 
	do
		dirName=${dirArray[$x]}
		dirAttributes[1]=`ls -ld /${dirNameArray[$x]} | awk -F 'd' '{print $2}' | awk '{gsub(/.{3}/,"& ")}1'  | awk '{print $1 }' | awk '{gsub(/.{1}/,"& ")}1'`
		dirAttributes[2]=`ls -ld /${dirNameArray[$x]} | awk -F 'd' '{print $2}' | awk '{gsub(/.{3}/,"& ")}1'  | awk '{print $2 }' | awk '{gsub(/.{1}/,"& ")}1'`
		dirAttributes[3]=`ls -ld /${dirNameArray[$x]} | awk -F 'd' '{print $2}' | awk '{gsub(/.{3}/,"& ")}1'  | awk '{print $3 }' | awk '{gsub(/.{1}/,"& ")}1'`
 		echo -n ${dirAttributes[1]} " " ${dirAttributes[2]} " " ${dirAttributes[3]} "  "
	
		if [ "$x" = "2" ]; then # if we're on the first non-root directory, echo that
			echo $dirName
		else # else, echo the next directories
			echo $dirName | awk -F '/' '{print $2}'
		fi
		echo " "
		x=$[$x+1]
	done
	
	echo "Valid commands: u(p) d(own) q(uit)"
	read options

	if [ "$options" = "d" ]; then
	
		if (( "$currentLevel" < "$maxLevel" )); then
			currentLevel=$[$currentLevel+1]
			echo "The level is: " $currentLevel # for debugging
		fi

	elif [ "$options" = "u" ]; then
		if (( "$currentLevel" > "1" )); then
			currentLevel=$[$currentLevel-1]
			echo "The level is: " $currentLevel # for debugging
		fi
	elif [ "$options" = "q" ]; then
	exit 0;
	fi
done
